on: [push]

jobs:
  find-and-replace-job:
    runs-on: ubuntu-latest
    name: 'Find and replace on a string'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run find-and-replace to replace / with - (ref/heads/main -> ref-heads-main)
        uses: LarsenLP/actions-find-and-replace-string@3
        id: findandreplace
        with:
          source: ${{ github.ref }}
          find: '/'
          replace: '-'
      - name: Get the above output
        run: echo "The replaced value is ${{ steps.findandreplace.outputs.value }}"